### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-ui#1]
```
/n-ui
|-- base
|   `-- integrations
|   `-- next
|-- components
|   `-- component-name
```

**Comment by wheresrhys** [comment]
```
/n-ui
|-- _shared
|-- component1
|-- component2
```

What would be in integrations, and what in next in your implementation?

**Comment by i-like-robots** [comment]
integrations: setup of external deps, E.G. o-grid, o-typography and o-colors
next: don't know. It may be a bit of a dumping ground for our Next-only mixins or something.
