### ISSUE TITLE
Split myft feature into separate concerns

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/n-ui#125]
Seems to be three different bits to it
- follow buttons
- email sign up
- list creation

Only the myft page needs the list creation, and the last two are definitely no critical, so would be good to split into separate features

@Financial-Times/next-myft

**Comment by laurieboyes** [comment]
Yeah sounds very sensible. Although I'd probably organise it more like this:
- follow
- save
- preferences (this incorporates email sign up)
- lists

(Actually could maybe combine follow and save as they very often come together and are both just buttons?)

**Comment by ironsidevsquincy** [comment]
Yep, sounds good. Basically, whatever allows apps to get just what they want, e.g. front page just wants follow buttons and the email sign up, and nothing else

**Comment by wheresrhys** [comment]
Also woudl be nice to follow the origami pattern of having the bits defined by classes available as sass mixins too

**Comment by bjfletcher** [comment]
:+1: this... I want just the follow button in the critical/head CSS for the stream page app
and not the whole myFT CSS

**Comment by bjfletcher** [comment]
head.css for stream:
194k with myFT
138k without myFT

the above shows the importance of this issue for performance

**Comment by laurieboyes** [comment]
😮  wow

**Comment by bjfletcher** [comment]
@laurieboyes heh - that was my reaction too :)

**Comment by ironsidevsquincy** [comment]
Coupled with https://github.com/Financial-Times/n-ui/issues/126, should be able to get it down a lot further

**Comment by wheresrhys** [comment]
follow + save buttons are now separated in to myft-core.
