### ISSUE TITLE
To-dos for v1.0.0

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-ui#13]
## Breaking API changes
- [x] Implement presets and options equivalent to the js api for bootstrap.scss
## Flatten the dependency tree
- [x] Integrate then deprecate n-layout
- [x] Integrate then deprecate next-sass-setup
- [x] Integrate then deprecate n-normalize
- [x] Integrate then deprecate n-util
- [x] Integrate and deprecate next-js-setup
## Documentation
- [x] Update readme
- [x] Add migration wiki page
- [x] Add 'critical' CSS wiki page (maybe?)
## Tooling
- [x] Get Sass and JS linting in place
- [x] Declare options in a json consumable by js and sass (more a n-makefile thing, nice to have)
## Modules to import/wrap
- [x] ads - leave til last (liable to change)
- [x] buttons
- [ ] card
- [x] colors
- [x] cookie-message
- [x] date
- [x] expander
- [x] footer
- [ ] forms
- [x] grid
- [x] header - leave til last (nav team working on it constantly)
- [x] icons
- [x] layout
- [x] myft
- [x] normalize
- [x] notification
- [x] overlay
- [x] tracking
- [x] typography
- [x] utils
- [x] viewport
- [x] welcome-message

**Comment by ifyio** [comment]
I removed the `message-prompts` todo entry in 'Modules to import/wrap' as the code has been retired https://github.com/Financial-Times/n-ui/pull/554
