### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-ui#246]
It's come up a few times that configuration of n-ui is confusing people. The JavaScript side is quite self-explanatory but the Sass side is not. Originally it was intended that both should follow the same API (as close as possible) but naturally they have diverged.

The `$_n-ui-features` map lists all of the available modules and their default values. There are two confusing aspects to this:

1. 'primitive' modules (those within `env.scss`) are not meant to be configurable
2. The values are not boolean but may be `true`, `false` _or_ `'critical'`

Because of reason 2 it is not possible to sort out 1.

I think something like the following may be clearer: 

```scss
// declare only the configurable features
$_n-ui-features: (
	ads: true,
	buttons: false,
	cookieMessage: false,
	expander: false,
	footer: true,
	forms: false,
	header: true,
	layout: true,
	messagePrompts: false,
	myft: false,
	notification: false,
	overlay: false,
	promoMessages: false,
	welcomeMessage: true
) !default;

// declare default critical features
$n-ui-critical-features: (
	ads, grid, header, layout, normalize, typography, utils
) !default;
```

With usage as following, with the addition of a separate `critical` parameter:

```scss
@include nUiConfigure((
  preset: 'complete',
  features: (
    cookieMessage: true
  ),
  critical: (
    cookieMessage
  )
);
```

**Comment by i-like-robots** [comment]
http://www.sassmeister.com/gist/f7447023fc69b1daa6540732834e9a87

**Comment by ironsidevsquincy** [comment]
Not sure this is making it simpler. Haven't heard any issues around it being currently confusing, but maybe I'm just missing out on the chatter

1) Everything should be configurable, i.e. some pages don't need ads, util, header, etc, so to future-proof, every feature should have the ability to turn off
2) Personally, quite like the current configration values, i.e. a feature having three states, keeps everything in a easy to parse single list

So my 2p is to leave the api as it is

**Comment by wheresrhys** [comment]
I'm not eager for a change either. Current config hasn't had a chance to settle in yet, and we're not sure all the use cases we need to cover have been addressed. Better to react to new requirements as they come in for a while, and then if at the 'end' of it we have something that's a bit of a mess, then I think we can justify a refactor & API tidy

**Comment by i-like-robots** [comment]
@ironsidevsquincy 1. yes, 2. reminds me of eslint settings 
@wheresrhys sounds sensible

This was somewhat reactionary after being on the receiving end of complaints/frustrations a couple of times.

**Comment by ironsidevsquincy** [comment]
tbh, I think we should get rid of this 'up-front' way of configuring deps completely. 
If we just `@import` exactly what we need in the file that needs it, we 
 * wouldn't have to worry about setting a dep as `critical`, etc, as that would just work as virtue of it being in the critical block or not
 * wouldn't have to worry about defineing dep's dependencies
 * wouldn't need to worry about unused deps being left behind when a component doesn't use it anymore. Currently, if we configure an app as needing `o-buttons`, I have no idea what needs it/if it's still needed, etc

The only issue we'd have to solve is a module being required twice, the first as non-critical, the second as critical. With our deduping, only the first one would be output, whereas we'd want the critical one to be output.

**Comment by wheresrhys** [comment]
... but that's dangerously close to the free for all it was before. Having a fairly simple api to include core stuff in one place discourages (I hope) them from being included all over the place and lingering around long after they're needed. I think the parity between js and Sass APIs for n-ui is valuable too

not sure I understand your second 2 points

**Comment by ironsidevsquincy** [comment]
Was that a bad thing, including in the place you need it? Seems natural to me, how `@import`s and `require`s work. We're now separating the place it's needed from where it's included, and I'm not sure what the benefit is

Plus if we do use the standard `@import`, we need to use this horrible call - https://github.com/Financial-Times/next-stream-page/blob/11757c7ec1ee5ba0ca5f9631cdca84ba3f972d13/shared/components/pagination/_main.scss#L1

**Comment by wheresrhys** [comment]
Having discussed it I'm coming round to your way of thinking. Will open an issue to discuss solutions to the output critical & non-critical leading (sometimes) to non-critical only
