### ISSUE TITLE
Potential breaking change for v1

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-ui#36]
`/*#{nUiStartCritical()}*/` is brittle as an extra space at the start means it won't work. Can it output the entire comment instead?

@i-like-robots @ironsidevsquincy

**Comment by i-like-robots** [comment]
Would have to be a mixin - if it's more robust I say yeah

**Comment by ironsidevsquincy** [comment]
👍 for something else, syntax is a bit esoteric atm - mixin would be good

**Comment by wheresrhys** [comment]
ok. I can make it a non breaking change as functions and mixins can share names, but I will only document the mixin for v1
