### ISSUE TITLE
Hide "Add to myFT" button until its styling is settled

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/n-ui#407]
If you've already subscribed to a tag, when you load a page, the button briefly appears as "Add to myFT", then it changes to "Added" (with a transition effect as if you clicked it).

![image](https://thumbs.gfycat.com/AgitatedBarrenBudgie-size_restricted.gif)

Can we change it so the button starts out with `display: none` on page load (for js-supporting browsers at least), then unhide it when its label and styling are settled?

**Comment by wheresrhys** [comment]
@Financial-Times/next-myft one for thursday afternoon?

**Comment by keirog** [comment]
Thanks, yep; we’ve added it to our Trello board
