### ISSUE TITLE
Check a11y for these components

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/n-ui#556]
pa11y checks a test page in every build (ie https://n-ui.ft.com/n-ui/test-page/2696/test-page.html). The following components are not included in that check but may need to be:

No HTML templates but either react-y or have markup in the JS in some other way:
- tour-tip
- subscription-offer-prompt

Have HTML templates
- layout/wrapper?
- myft
- myft-digest-promo

cc @pixelandpage myft bits and pieces in n-ui ^^

**Comment by keirog** [comment]
TODO:
- [ ] tour-tip
- [ ] subscription-offer-prompt
- [ ] layout/wrapper (handles header + footer)
- [ ] layout/vanilla?
- [ ] myft-common
- [ ] myft-digest-promo
- [ ] myft-hint
- [ ] welcome-message
