### ISSUE TITLE
Update o-icons to new icon set

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/n-ui#573]
nui is currently using the old icon set which has been replaced by a new one.
All origami components now use the new one, so on the live site next has a mix of the old set and the new set.

![screen shot 2016-10-19 at 10 48 40](https://cloud.githubusercontent.com/assets/68009/19514008/ee9f940c-95e9-11e6-9c34-5df81b88ed52.png)

**Comment by wheresrhys** [comment]
done... I think. please reopen if not
