### ISSUE TITLE
n-ui-env

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-ui#68]
because of `n-ui/env` we now have a horrible circular dependency that needs to be got rid of to bring a new component in to n-ui

i.e. n-my-component includes `n-ui/env`in order to avoid declaring o-grid, o-buttons etc as dependencies. If we want to bring n-my-component in to n-ui we must do everything in one fell swoop - just proxying through to it and doing so gradually is not possible -because then we would have a circular dependency n-ui requires n-my-component requires n-ui/env

This obviously wouldn't be circular if we take n-ui-env out into a separate component

It would contain:

- much of n-ui/configure (though, if it can at all be avoided, not the `nUiConfigure` mixin)
- everything else from here https://github.com/Financial-Times/n-ui/blob/master/env.scss, n-ui would then proxy through to n-ui-env for these

thoughts? @i-like-robots @ironsidevsquincy

**Comment by i-like-robots** [comment]
I don't think components _need_ to rely on n-ui at all. Their demos may rely on it but that should be a separate concern.

Do you have an example in mind where this is a problem?

**Comment by wheresrhys** [comment]
nothing using e.g. o-grid mixins will pass CI unless they either explictly import o-grid or n-ui/env or (as I suggest) n-ui-env/main

**Comment by i-like-robots** [comment]
So my thoughts are:

1. For the problem components add n-ui to `devDependencies`
2. Add a `demo.scss` file that imports `n-ui/env` and `./main`
3. Switch CI to build `demo.scss` rather than `main.scss`

For step 3 I don't know the overhead, I guess just customising the Makefile?

**Comment by wheresrhys** [comment]
Feels like it'd add complexity

@ironsidevsquincy do you have any opinion?

**Comment by i-like-robots** [comment]
In defense of it - because it's completely explicit I don't think it adds complexity. What attracted me to suggest such a pattern is that there's nothing clever and/or brittle to break because it circumvents the issue entirely.

**Comment by ironsidevsquincy** [comment]
Feels like this would be more misleading - some components _do_ depend on other modules, assuming the client will have these dependencies already seems more brittle. What's the argument against just pulling requiring what it needs (e.g. `o-grid`) rather than `n-ui`?

**Comment by i-like-robots** [comment]
https://github.com/Financial-Times/n-ui/pull/81#discussion_r65909277

![jam it](http://i.giphy.com/3oGRFAs1EuQzvuYEHm.gif)

**Comment by i-like-robots** [comment]
> What's the argument against just pulling requiring what it needs (e.g. o-grid)

Several components are configured specifically for Next's usage - grid being on of them. Depending on n-ui also flattens and simplifies the dependency tree.

> Add n-ui to `devDependencies`

This breaks semver too so potentially not safe... though perhaps only marginally worse than resolving to a specific version in the Bower manifest.

**Comment by i-like-robots** [comment]
What if we add `n-ui` to the `ignoredDependencies` field of n-ui's Bower manifest?

**Comment by wheresrhys** [comment]
oooh, I like if it works

On Mon, 6 Jun 2016 at 18:43 Matt Hinchliffe <notifications@github.com>
wrote:

> What if we add n-ui to the ignoredDependencies field of n-ui's Bower
> manifest?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Financial-Times/n-ui/issues/68#issuecomment-224032548>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAbUR5i7dy1C_Qr1YeivPOlMyxGPRuIvks5qJFwkgaJpZM4IsRdq>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by i-like-robots** [comment]
https://github.com/Financial-Times/n-ui/pull/85

**Comment by wheresrhys** [comment]
resolved
