### ISSUE TITLE
CSS entry points

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-ui#8]
Looking right now we have:

- bootstrap.scss
- critical.scss
- main-ie8.scss
- non-critical.scss

I guess there are a few q's about that:

- where is main.scss?
- should 'critical' styles be be left up to the consuming app?
- should we generate the IE stylesheet as suggested [here](https://github.com/Financial-Times/next-sass-setup/pull/111)?

**Comment by i-like-robots** [comment]
The way I kind of see this working is like we had at LP which is the distinction of a 'core' and 'components'.

Core included the bootstrapping, low level styles and primitives. All components were opt-in by the consuming app. For example:

```
`
|- core
|      setup
|      layout
|      grid
|      typography
|      buttons
|      utils
|      date
|      ads
|- components
|      card
|      expander
|      forms
|      welcome-message
|      cookie-message
|      header
|      footer
```

And an app using n-ui:

```scss
@import "n-ui/core";
@import "n-ui/header/main";
@import "n-ui/footer/main";
@import "n-ui/header/card";
```

**Comment by wheresrhys** [comment]
main entry point = bootstrap
possibly temporaril remove ie8 variant for sanity reasons
rename core => __ something else

**Comment by wheresrhys** [comment]
I think we have a reasonably good thing now
