### ISSUE TITLE
Cannot npm link into app

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-ui#887]
When NPM linking n-ui into a local app for testing things go pretty pear shaped - at least for the front page app due to dependency resolution issues.

Given:

```sh
$ cd next-front-page && npm link @financial-times/n-ui && make run
```

This is what happens:

1. The app requires app shell from n-ui 
2. n-ui requires n-express but resolves to the version installed local to itself (A), not the one installed in the app's node modules (B)
3. n-express (A) requires the flags client local to itself (C) and initialises it
4. The app requires the flags client but this time it gets the one local to itself (D), not the one n-ui included (C)
5. The app explodes because this version of the client flags client (D) has not been initialised

I've been able to work around the flags issue which allows the app to start however the template paths cannot be reconciled.

I'm not sure if this is even fixable without lots of hacks =/

**Comment by wheresrhys** [comment]
Does the app declare the flags client as a direct dependency in its package.json? If it doesn't then I think this is expected behaviour. What does the app use flags client directly for?

What about template paths. Is it n-teaser related?

**Comment by i-like-robots** [comment]
1. Yes, I assume it relies on NPM installing dependencies with maximum flatness - not a safe strategy for something not idempotent.
2. I didn't look into this fully, I can't remember if it was specifically teasers or otherwise but I will find out.

**Comment by wheresrhys** [comment]
Does the app explicitly init the flags client? Again, if it's using it as a direct dependency it probably should (instead of relying on n-express to do so). A double init has no adverses side effects AFAIK

**Comment by wheresrhys** [comment]
I'm in favour of defining metrics, logger and flags as globals in next apps. Would remove a lot of verbosity and avoid issues like this

**Comment by wheresrhys** [comment]
Closing as it's not really a bug in n-ui. Error message in flags client is far more explicit about the rot cause now
