### ISSUE TITLE
Add bower ignore/npm ignore rules

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-ui#910]
I think there may be issues when disambiguating (is that a word?) templates sometimes. It appears as though templates are preferred from the NPM dependency rather than Bower but not always (depending on how an app references the I reckon).

- Add `browser/layout` to the Bower manifest ignore list
- Add `browser/bootstrap` to .npmignore

Then for good measure:

- Add `server/` to the Bower manifest ignore list

**Comment by wheresrhys** [comment]
Yasss! I tried this once on an older version, but was way too tangled. It could well be feasible nowadays
